### ISSUE TITLE
USER STORY: View a Recipe page

### ISSUE THREAD

**Issue by cameronk97** [cameronk97/The_Recipe_Book#18]
EPIC #15 

As a **user**, I can **click on a recipe listed on the homepage to view its individual recipe page**, so that I can **see detailed information about the recipe**.

**Tasks:**
- [ ] Implement views to display individual recipe pages.
- [ ] Retrieve recipe data from the database or an API.
- [ ] Create a template based on the wireframes for displaying detailed information about a recipe.
- [ ] Create a URL pattern to handle recipe page requests using a slug field.

**Acceptance Criteria:**
1. Users can access individual recipe pages by clicking on the title or Image of a recipe post displayed on the homepage.
2. The URL structure for recipe pages includes a unique slug field for each recipe post.
3. The recipe detail page displays the relevant, detailed recipe information for all users.
