### ISSUE TITLE
USER STORY: Site Admin CRUD Operations

### ISSUE THREAD

**Issue by cameronk97** [cameronk97/The_Recipe_Book#2]
EPIC: #1 

As a **site administrator**, I can **perform CRUD operations (Create, Read, Update, Delete)** on site content, so that I can **manage the website efficiently**.

**Tasks:**
- [x] Implement built-in Django User model.
- [x] Create the Recipe model.
- [x] Create the Saved Recipes model.
- [x] Create a Superuser account.
- [x] Implement CRUD (Create, Read, Update, Delete) operations for site administrators.

**Acceptance Criteria:**
1. The admin site can be accessed by the superuser.
2. Site Administrators can create recipes on the admin site.
3. Site Administrators can read recipes on the admin site.
4. Administrators can update recipes on the admin site.
5. Administrators can delete recipes on the admin site.
