### ISSUE TITLE
USER STORY: 'My Recipes' Section

### ISSUE THREAD

**Issue by cameronk97** [cameronk97/The_Recipe_Book#24]
EPIC #23 

As a **logged in user**, I can **view all of the recipes I have posted in one place**, so that I can **easily access and manage my own recipes**.

**Tasks:**
- [ ] Query the database for recipes associated with the current user.
- [ ] Display the user's recipes on the profile page.
- [ ] Implement a "Post a New Recipe" button.
- [ ] Ensure clicking on a recipe title or image directs the user to the recipe detail page.

**Acceptance Criteria:**
1. Users can see a list of their posted recipes in the "My Recipes" section on their Profile page.
2. Clicking on a recipe title or image navigates the user to the recipe detail page.
3. Clicking on a recipe title or image navigates the user to the recipe detail page.
4. The section includes options for users to edit or delete their recipes in the My Recipes section using appropriate icons.
