### ISSUE TITLE
USER STORY: UX and Design

### ISSUE THREAD

**Issue by cameronk97** [cameronk97/The_Recipe_Book#36]
EPIC #34 

As a **Site User**, I can **enjoy visually appealing design and smooth user interface interactions**, so that **my overall experience on the platform is positive, appealing and smooth**.

**Tasks:**
- [x] Add necessary Bootstrap CDN links to base.html file.
- [ ] Style your html and set up the layout using bootstrap classes.
- [x] Set up Font Awesome so that you can add icons to your site.
- [ ] Improve the design and UX of the site so that everything is visually appealing.

**Acceptance Criteria:**
1. Bootstrap is set up and working properly.
2. HTML is styled nicely using Bootstrap classes.
3. Font Awesome is implemented properly.
4. Font Awesome icons are displaying correctly on the site and add to the visual appeal and overall UX of the site.
5. The design and UX of the site is attractive, appealing and intuitive for all users.
