### ISSUE TITLE
DEVELOPER TASK: Connect Database & Setup Back-End

### ISSUE THREAD

**Issue by cameronk97** [cameronk97/The_Recipe_Book#5]
EPIC #1 

As a **developer** I can **capability** so that **received benefit**

As a **developer**, I can **connect the database and set up the back-end**, so that **the web application can store and retrieve data**, enabling users to interact with the application and access dynamic content.

**Tasks:**
- [ ] Make initial migrations.
- [ ] Create a PostgreSQL database.
- [ ] Create an env.py file.
- [ ] Connect to remote database.

**Acceptance Criteria:**
1. Acceptance criteria 1.
2. Acceptance criteria 2.
3. Acceptance criteria 3.
